# Generated by Django 6.0 on 2025-12-17 19:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('field', models.CharField(choices=[('IT', 'IT'), ('Mechanical', 'Mechanical Engineering'), ('Electrical', 'Electrical Engineering'), ('Architecture', 'Architecture'), ('Civil Engineering', 'Civil Engineering'), ('Biomedical', 'Biomedical Engineering'), ('Marketing', 'Marketing'), ('Finance', 'Finance')], max_length=50)),
                ('description', models.TextField()),
                ('internship_start', models.DateField()),
                ('internship_end', models.DateField()),
                ('monthly_salary', models.IntegerField(validators=[django.core.validators.MinValueValidator(300)])),
                ('duration_in_weeks', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(4)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Nominated', 'Nominated'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Completed', 'Completed internship')], max_length=50)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship_app.candidate')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship_app.internship')),
            ],
        ),
    ]
