# Generated by Django 6.0 on 2025-12-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='title',
            new_name='referent_number',
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
