# Generated by Django 5.2.9 on 2025-12-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0003_alter_application_id_alter_candidate_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='field',
            field=models.CharField(choices=[('IT', 'IT'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Architecture', 'Architecture'), ('Civil Engineering', 'Civil Engineering'), ('Biomedical Engineering', 'Biomedical Engineering'), ('Marketing', 'Marketing'), ('Finance', 'Finance')], max_length=50),
        ),
    ]
